openapi: 3.0.1
info:
  title: jwthandling
  description: API Definition of jwthandling
  version: 1.0.0
servers:
- url: http://localhost:8290/testjwt
paths:
  /:
    get:
      responses:
        default:
          description: Default response
