openapi: 3.0.1
info:
  title: choreoStaticJSON
  description: API Definition of choreo test endpoint returning JSON object
  version: 1.0.0
servers:
- url: http://localhost:8290/singleJSONResponse
paths:
  /:
    get:
      responses:
        default:
          description: Default response
